### ISSUE TITLE
The data is not updated while ws is running

### ISSUE THREAD

**Issue by ninedraft** [containerum/nodemetrics#11]
The FromToStep struct is initialized before WS cycle, every message will contain the same dataframe as previous

https://github.com/containerum/nodeMetrics/blob/1a767971bc1e059306b859c057aa18542db184e2/pkg/service/handlers/cpu/history.go#L80

**Comment by Iliad** [comment]
fromToStep инициализируется до цикла, но в конце каждого цикла https://github.com/containerum/nodeMetrics/blob/1a767971bc1e059306b859c057aa18542db184e2/pkg/service/handlers/cpu/history.go#L94-L96
